### ISSUE TITLE
Rmd files link - 404 Error

### ISSUE THREAD

**Issue by TomMonks** [drvinceknight/amwoss#140]
The R markdown link in `amwoss/examples/readme.md` is broken.  When clicked it produces a 404 error. 

Steps to reproduce:

1. go to https://github.com/drvinceknight/amwoss/tree/main/examples
2. In the readme.md preview click `Rmd files`

This is attempting to open `https://github.com/drvinceknight/amwoss/blob/main/examples/rmd`

**Comment by drvinceknight** [comment]
Thanks @TomMonks, we're aware of this and will fix. 👍
