### ISSUE TITLE
Running title is too long for header

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/amwoss#16]
In e499081 I've added the style files, the running header title is too long to fit. There is information about how to deal with this in the attached pdf.
[TF LaTex_Manuscript Preparation Guidelines.pdf](https://github.com/drvinceknight/amwoss/files/3777891/TF.LaTex_Manuscript.Preparation.Guidelines.pdf)

**Comment by geraintpalmer** [comment]
Solved with  b52fd18
