### ISSUE TITLE
GP read over Chapter 3

### ISSUE THREAD

**Issue by geraintpalmer** [drvinceknight/amwoss#27]
+ section 3.1:  `The mathematical tool used to model this situation is a Markov Processes.` - capitalisation and plural process. ✅ 
+ section 3.2:: Can we add an explanation why the state space if finite, and why 6? Half a sentence, just to complete the explanation. ✅ 
+ section 3.3: `We see that no matter what state (column) the system is in...` I know why it says column, but that's really not obvious from the way the matrix is printed. ✅ 
+ section 3.3: `In fact the only way to lower the probability of the shop being full below the 10%
threshold is to have barbers work at the faster rate of 4.6 customers per time unit:` - In the R section you mention `waiting_room = 20`, here you don't. Also its not the *only* way, but a way right? (same with section 3.4 in R bit). ✅

**Comment by drvinceknight** [comment]
- Simplify docstrings to not be repetitive.

**Comment by drvinceknight** [comment]
- Put library imports in same code block

**Comment by drvinceknight** [comment]
- use `num_` instead of `number_of`
- Tidy code prints with multiple steps.

**Comment by drvinceknight** [comment]
- Fix line 497 and similar
