### ISSUE TITLE
Questions / Code Principles after reading over the code

### ISSUE THREAD

**Issue by geraintpalmer** [drvinceknight/amwoss#75]
Some specific questions abound Heuristics chapter:
- In the function `swap_stops` why do `i` and `j` need to be sorted? Can this be removed?
- In the function `reverse_path` can sampling `i` and `j`, and sorting `i` and `j` be separated? On separate lines?
- In the `run_neighbourhood_search` Python function, I think it would be much more readable without the walrus operator, setting the cost and comparing the cost on separate lines. I think this might also save us a line of code.

Some general questions / potential principles to follow:
(for these I'm pretty agnostic. We should be consistent. And am also trying to reduce the number of lines so that the code blocks fit nicely).
- Blank lines in docstrings? They are taking up space.
- Blank lines in the functions? When are they appropriate? Again, they are taking up space.
- I think we should only break a line _if_ it results in a line that's too long. e.g.
  ```
  x = my_function(time=40, rate=5)
  ```
  not
  ```
  x = my-function(
    time=40
    rate=5
  )
  ```
  Similarly, what should we do if we can fit some of the arguments in the line, but not others?, e.g can we do:
  ```
  x = my_function(time=40,
    rate=5
  )
  ```
  ? And what if there's more? Can we do:
  ```
  x = my_function(time=40, rate=5,
    c=c, vaccine_rate=vaccine_rate,
    another_argument=another_argument
  )
  ```
  ? Sometimes there are many short arguments, each with their own line, which I think looks a little silly and takes up space.
- In R (http://adv-r.had.co.nz/Style.html), indentation is _always_ 2 spaces. The _only_ exception is when listing arguments of a function when we define it. We have forgotten this a lot, best go through and check.
- Generally better to write one function/class per code block. Start a new code block if we are then going to run that function.

**Comment by geraintpalmer** [comment]
Also, a principle we started the book with:

A function should take arguments it needs, e.g. those that we will change. The Markov Chain chapter is a really good example of this. The only arguments the functions take are `waiting_room=4, num_barbers=2`; other variables, e.g. arrival rate and service rate, are hard coded inside the function.

**Comment by drvinceknight** [comment]
> Some specific questions abound Heuristics chapter:
> 
> * In the function `swap_stops` why do `i` and `j` need to be sorted? Can this be removed?

No it can cause problems for some seeds if j is sampled in a way that it is smaller than i.


> * In the function `reverse_path` can sampling `i` and `j`, and sorting `i` and `j` be separated? On separate lines?

Sure.

> * In the `run_neighbourhood_search` Python function, I think it would be much more readable without the walrus operator, setting the cost and comparing the cost on separate lines. I think this might also save us a line of code.

More readable because of the limited horizontal space?

> 
> Some general questions / potential principles to follow:
> (for these I'm pretty agnostic. We should be consistent. And am also trying to reduce the number of lines so that the code blocks fit nicely).
> 
> * Blank lines in docstrings? They are taking up space.

This is sucky because the blank lines help with readability but we're short on space. I'd prefer to leave them in.

> * Blank lines in the functions? When are they appropriate? Again, they are taking up space.

This is probably to be sorted on a case by case basis:

- Appropriate when they help break up steps in code that can't otherwise be modularised.

> * I think we should only break a line _if_ it results in a line that's too long. e.g.
>   ```
>   x = my_function(time=40, rate=5)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   not
>   ```
>   x = my-function(
>     time=40
>     rate=5
>   )
>   ```

Sure.

>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Similarly, what should we do if we can fit some of the arguments in the line, but not others?, e.g can we do:
>   ```
>   x = my_function(time=40,
>     rate=5
>   )
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   ? And what if there's more? Can we do:
>   ```
>   x = my_function(time=40, rate=5,
>     c=c, vaccine_rate=vaccine_rate,
>     another_argument=another_argument
>   )
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   ? Sometimes there are many short arguments, each with their own line, which I think looks a little silly and takes up space.
> * In R (http://adv-r.had.co.nz/Style.html), indentation is _always_ 2 spaces. The _only_ exception is when listing arguments of a function when we define it. We have forgotten this a lot, best go through and check.

So there's a number of objective reasons why having long lines of single variables:

- Easier to see the variables: they're either all in one horizontal or one vertical line. Basically: function signatures are always in a line, whether or not it is horizontal or vertical depends on horizontal space. Any other way of writing them leaves you open to misreading.
- Better (arguably necessary) for version control (which is not immediately relevant here but good to only show best practice).
- By having them on a single line this becomes equivalent to "hard coding" variables in functions which we should avoid (which is relevant to https://github.com/drvinceknight/amwoss/issues/75#issuecomment-921674486)

There is a reason black auto formats like this, it is objectively better in a number of ways so we should do it that way.

> * Generally better to write one function/class per code block. Start a new code block if we are then going to run that function.

Yup. 100%

**Comment by drvinceknight** [comment]
> In R (http://adv-r.had.co.nz/Style.html), indentation is always 2 spaces. The only exception is when listing arguments of a function when we define it. We have forgotten this a lot, best go through and check.

Missed that in my response above: yup sounds good. I have definitely forgotten it more or less universally.

**Comment by drvinceknight** [comment]
> Also, a principle we started the book with:
> 
> A function should take arguments it needs, e.g. those that we will change. The Markov Chain chapter is a really good example of this. The only arguments the functions take are `waiting_room=4, num_barbers=2`; other variables, e.g. arrival rate and service rate, are hard coded inside the function.

I really don't think we should hard code variables anywhere. Hardcoding a variable is equivalent (in terms of lines of code) to setting a default which is better... Then "A function should take arguments it needs" just becomes equivalent to "A function should only have non default arguments it needs". Whatever we decide, we should aim to be consistent across all the chapters and write these principles up somewhere...

**Comment by geraintpalmer** [comment]
> > In the function swap_stops why do i and j need to be sorted? Can this be removed?

> No it can cause problems for some seeds if j is sampled in a way that it is smaller than i.

Why is this?
I can't see logically why this should break. Does this indicate that there's something else wrong/a better way to do it?

**Comment by geraintpalmer** [comment]
> > Blank lines in docstrings? They are taking up space.

> This is sucky because the blank lines help with readability but we're short on space. I'd prefer to leave them in.

Cool, I'll leave them in. Maybe on the one or two codeblocks that are too long we can try and reduce the number of lines needed in the writing of the docstrings.

**Comment by drvinceknight** [comment]
> Why is this?
> I can't see logically why this should break. Does this indicate that there's something else wrong/a better way to do it?

It is to do with the swap operators further down the process. When you're slicing a tour you're inherently assuming that i is less than j (something like `tour[1, i] + tour[j, i] + ...` falls over if j  is less than i. You could theoretically slice in two different ways but that's not a nice way of doing it so it makes to sort them and then it just makes sense to sort them right at the start.

**Comment by geraintpalmer** [comment]
> > In the run_neighbourhood_search Python function, I think it would be much more readable without the walrus operator, setting the cost and comparing the cost on separate lines. I think this might also save us a line of code.

> More readable because of the limited horizontal space?

Party.

But also clearer what's going on. The if statement becomes more readable `if cost <= best_cost` reads like English in my opinion.

I like that each line does one thing and one thing good. But that's just my preference.

Putting them on separate lines would also save us 1 line too. Something that in this codeblock would be useful.

**Comment by geraintpalmer** [comment]
> It is to do with the swap operators further down the process. When you're slicing a tour you're inherently assuming that i is less than j (something like tour[1, i] + tour[j, i] + ... falls over if j is less than i. You could theoretically slice in two different ways but that's not a nice way of doing it so it makes to sort them and then it just makes sense to sort them right at the start.

Ok. As we've moved things around and we don't directly compare `swap_stops` and `reverse_path` anymore, does this matter?

**Comment by drvinceknight** [comment]
I don't understand: we do still compare them. 

Either way it matters, one of those two (I forget which, perhaps even both) does not work if the i and j are not sorted.

Is there a reason you'd prefer not to sort them (arguably it's just cleaner to return a sorted tuple no matter the use case)?

**Comment by drvinceknight** [comment]
> Party.
> 
> But also clearer what's going on. The if statement becomes more readable `if cost <= best_cost` reads like English in my opinion.

If you read the walrus operator using "defined by" (which I that notation is sometimes used to indicate) then it reads just fine.

> 
> Putting them on separate lines would also save us 1 line too. Something that in this codeblock would be useful.

I'm not terribly bothered by using the walrus operator or not (but in some cases it does make code so much cleaner and clearer). I'd prefer to keep it as it shows off a nice bit of modern mathematical python but if you're very keen to get rid of the extra line I won't insist on it.

**Comment by geraintpalmer** [comment]
> I really don't think we should hard code variables anywhere. Hardcoding a variable is equivalent (in terms of lines of code) to setting a default which is better... Then "A function should take arguments it needs" just becomes equivalent to "A function should only have non default arguments it needs". Whatever we decide, we should aim to be consistent across all the chapters and write these principles up somewhere...

I remember our line of thinking being, how do we decide what an argument should be? e.g. With the DES chapter there are so many things that could be an argument, where is the line? The list of arguments would be very long. I think we were trying to save space and readability.

Maybe just take it case by case?

`distance_matrix` in the heuristics chapter would be silly to hard code, so makes sense to make that an argument, even though we never change it. But then should the DES transition matrix be an argument? I don't think do.

**Comment by drvinceknight** [comment]
> I remember our line of thinking being, how do we decide what an argument should be? e.g. With the DES chapter there are so many things that could be an argument, where is the line? The list of arguments would be very long. I think we were trying to save space and readability.
> 
> Maybe just take it case by case?

Sure case by case makes sense but I'd suggest the principle is to use a default argument preferably but to hard code if there's a reason to.

Essentially, if in the code we have:

```
    a = 5
```

that should just be in the function signature:

```
def ...
     a=5,
```

This would ensure it's better documented in the doctoring as well.

> But then should the DES transition matrix be an argument? I don't think do.

Yeah this is a good example. The DES transition matrix here is so specific to the problem that it makes sense not to be hard coded.

**Comment by geraintpalmer** [comment]
> I don't understand: we do still compare them.
> Either way it matters, one of those two (I forget which, perhaps even both) does not work if the i and j are not sorted.
> Is there a reason you'd prefer not to sort them (arguably it's just cleaner to return a sorted tuple no matter the use case)?

`reverse_path` needs a sorted tuple.
`swap_stops` doesn't need it sorted. And not sorting them shouldn't change any outcome, the same seed gives the same swap. So I feel there's an extra piece of logic there, doing nothing, and taking up a line, that would be cleaner to remove.

**Comment by geraintpalmer** [comment]
I'll remove the warlus operator in a separate commit, see what you think, and you can rebase it then if not.

**Comment by drvinceknight** [comment]
> doing nothing,

disagree, it's the same amount of lines (it would need to be in `reverse_path`).

> cleaner to remove.

disagree it's cleaner to have the logic in the lower level function, if someone wrote a different one that needs to have sorted.

In essence:

A. In the book it makes no difference (the line of code would need to be there somewhere).
B. This makes the code more extendable : for every other swap operator you'd possibly need to re sort. You would end up moving the sort to where it is now.

**Comment by drvinceknight** [comment]
> Yeah this is a good example. The DES transition matrix here is so specific to the problem that it makes sense not to be hard coded.

The more I think about it the more the transition matrix is a really nice example: what have hard coded is the structure of the matrix *but* I think we should move the other hard coded variables to being defaults:

```
    arrival_rate = 15
    inspection_rate = 20
    repair_rate = 10
    prob_need_repair = 0.8
```

**Comment by drvinceknight** [comment]
> > doing nothing,
> 
> disagree, it's the same amount of lines (it would need to be in `reverse_path`).
> 
> > cleaner to remove.
> 
> disagree it's cleaner to have the logic in the lower level function, if someone wrote a different one that needs to have sorted.
> 
> In essence:
> 
> A. In the book it makes no difference (the line of code would need to be there somewhere).
> B. This makes the code more extendable : for every other swap operator you'd possibly need to re sort. You would end up moving the sort to where it is now.

This was all BS, I had not read the code you were talking about so I was not making sense.
